# -*- coding: utf-8 -*-
"""Requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OmPJzKhrV7hsekn92pxYB0MNBn1mQAvN
"""

# Write the updated requirements.txt file
with open("requirements.txt", "w") as f:
  f.write("streamlit\npandas\ndateparser\nplotly")

# Download the file
from google.colab import files
files.download("requirements.txt")